name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Login to GitHub Packages
      run: docker login -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/woovie/mtasa-wiki/mtasa-wiki:master
    - name: Push the Docker image to Docker Packages
      run: docker push docker.pkg.github.com/woovie/mtasa-wiki/mtasa-wiki:master
